### ISSUE TITLE
Project does not build with Make, likely because srce/SAM is a a git submodule

### ISSUE THREAD

**Issue by ChocolateMagnate** [Kishlay-notabot/perpetual-energy-machine#14]
I have cloned the repository but fail to build it using GNU Make:
```
[chocolate-magnate@millenium perpetual-energy-machine]$ make lure
make: *** No rule to make target 'reciter.o', needed by 'samlib.o'.  Stop.
```

Upon examination, it appears that the reciter.o file is located in the src/SAM directory. It can be viewed in GitHub but isn't otherwise cloned along with the project:

```
[chocolate-magnate@millenium perpetual-energy-machine]$ ls src/SAM/src
"src/SAM/src": No such file or directory (os error 2)
[chocolate-magnate@millenium perpetual-energy-machine]$ ls src/SAM
```

**Potential fix:**
1. Store the source code directly into the repository. It is feasible because the codebase is extremely small and we can allow it.
2. Dynamically link with samlib: expect users to install samlib using a package manager and compile the project to link with it loading the library at the runtime.
3. Build samlib as a dependency from a C package manager like Conon or vcpkg.

**Comment by TCA166** [comment]
Git submodules aren't cloned by default when you clone a repository.
Run this:

```
git submodule update --init
```

In project root and it should clone all submodules into their respective directories.
Including raw sourcecode when the source repository is public is bad practice IMO.

**Comment by ChocolateMagnate** [comment]
@TCA166 Thanks for the quick response! Unfortunately, the command fails with a permission error:

```
[chocolate-magnate@millenium perpetual-energy-machine]$ git submodule update --init
Submodule 'src/SAM' (git@github.com:vidarh/SAM.git) registered for path 'src/SAM'
Cloning into '/home/chocolate-magnate/Software-Engineering/Clones/perpetual-energy-machine/src/SAM'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:vidarh/SAM.git' into submodule path '/home/chocolate-magnate/Software-Engineering/Clones/perpetual-energy-machine/src/SAM' failed
Failed to clone 'src/SAM'. Retry scheduled
Cloning into '/home/chocolate-magnate/Software-Engineering/Clones/perpetual-energy-machine/src/SAM'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:vidarh/SAM.git' into submodule path '/home/chocolate-magnate/Software-Engineering/Clones/perpetual-energy-machine/src/SAM' failed
Failed to clone 'src/SAM' a second time, aborting
```

**Comment by TCA166** [comment]
Oh right... out of a force of habit I included the submodule using ssh. If you don't have ssh setup you will not be able to clone then. My bad didn't think about that. I will fix that soon by replacing the repo url in .gitmodules with the https link.
