### ISSUE TITLE
Feature Suggestion: Treadmills

### ISSUE THREAD

**Issue by NautaSquid** [Kishlay-notabot/perpetual-energy-machine#18]
We could alleviate user wear and injury greatly by using some sort of treadmill design to collect energy from users and as well as prevent them from making it up the hill.

**Comment by amamegs** [comment]
You are the smartest person I ever heard, amazing.

**Comment by sysadminmann** [comment]
That way the users would never reach the refreshment station and eventually decease. We cannot afford that to happen. 
Slightly less problematic: treadmills make noise, they would eventually be louder than the speakers can go and all would cease to exist.
